globalThis.PROJECTS = [
  {
    slug: "ttvnotifyme",
    theme: "Web & Erweiterungen",
    title: "TTVNotifyMe",
    status: "Finished",
    statusClass: "finished",
    description: "Eine einfache Browser-Erweiterung, die benachrichtigt, sobald ein Streamer live geht.",
    details: "TTVNotifyMe hält Streams im Blick, ohne dass die jeweilige Plattform dauerhaft geöffnet bleiben muss.",
    skills: ["JavaScript", "Browser Extension", "Notifications"],
    year: "2026",
    href: "https://github.com/DarkPlugins/TTVNotifyMe",
    download: "https://github.com/DarkPlugins/TTVNotifyMe/archive/refs/heads/main.zip"
  },
  {
    slug: "media-downloader",
    theme: "Web & Erweiterungen",
    title: "MediaDownloader",
    status: "Finished",
    statusClass: "finished",
    description: "Eine Browser-Erweiterung zum Herunterladen von Bildern und Videos direkt aus dem Kontextmenü.",
    details: "Medien können im Originalformat oder in unterstützten konvertierten Formaten gespeichert werden.",
    skills: ["JavaScript", "Browser Extension", "Media"],
    year: "2026",
    href: "https://github.com/DarkPlugins/MediaDownloader",
    download: "https://github.com/DarkPlugins/MediaDownloader/archive/refs/heads/main.zip"
  },
  {
    slug: "cr-toolkit",
    theme: "Web & Erweiterungen",
    title: "CR-Toolkit",
    status: "Active Development",
    statusClass: "active",
    description: "Eine Crunchyroll-Browser-Erweiterung mit zusätzlichen Steuerelementen für ein angenehmeres Anime-Erlebnis.",
    details: "Enthalten sind unter anderem ein anpassbarer Cinema-Modus, Intro- und Outro-Überspringen sowie Einstellungen für Kopfzeile und Oberfläche.",
    skills: ["JavaScript", "Browser Extension", "UI"],
    year: "2026",
    href: "https://github.com/DarkPlugins/CR-Toolkit",
    download: "https://github.com/DarkPlugins/CR-Toolkit/archive/refs/heads/main.zip"
  },
  {
    slug: "flipacoin",
    theme: "Web & Erweiterungen",
    title: "FlipACoin",
    status: "Finished",
    statusClass: "finished",
    description: "Eine kleine Website, die einen Münzwurf schnell und unkompliziert simuliert.",
    details: "Ein bewusst kompaktes Webprojekt, das eine einzelne Idee mit einer klaren Oberfläche umsetzt.",
    skills: ["JavaScript", "HTML", "CSS"],
    year: "2026",
    href: "https://github.com/DarkPlugins/FlipACoin",
    download: "https://github.com/DarkPlugins/FlipACoin/archive/refs/heads/main.zip"
  },
  {
    slug: "web",
    theme: "Web & Erweiterungen",
    title: "Web",
    status: "Finished",
    statusClass: "finished",
    description: "Die eigene Website als eigenständiges Webprojekt.",
    details: "Das Repository bündelt die Portfolio-Oberfläche und die dazugehörige Frontend-Umsetzung.",
    skills: ["HTML", "CSS", "JavaScript"],
    year: "2026",
    href: "https://github.com/DarkPlugins/Web",
    download: "https://github.com/DarkPlugins/Web/archive/refs/heads/main.zip"
  },
  {
    slug: "blacklist",
    theme: "Minecraft Plugins",
    title: "Blacklist",
    status: "Finished",
    statusClass: "finished",
    description: "Ein Minecraft-Plugin, das bestimmte Befehle wie /plugins oder /help für Spieler blockiert.",
    details: "Blacklist ist für deutschsprachige Server gedacht und konzentriert sich auf eine kleine, klar definierte Schutzfunktion.",
    skills: ["Java", "Minecraft", "Spigot"],
    year: "2026",
    href: "https://github.com/DarkPlugins/Blacklist",
    download: "https://github.com/DarkPlugins/Blacklist/archive/refs/heads/main.zip",
    spigotHref: "https://www.spigotmc.org/resources/blacklist-blocklist-de.114144/"
  },
  {
    slug: "relevant-commands-only",
    theme: "Minecraft Plugins",
    title: "RelevantCommandsOnly",
    status: "Not released yet",
    statusClass: "not-released",
    statuses: [
      { label: "Not released yet", className: "not-released" },
      { label: "Active Development", className: "active" }
    ],
    description: "Ein Minecraft-Plugin, das im Tab-Completer nur die Befehle aus den persönlichen Präferenzen anzeigt.",
    details: "Das Projekt befindet sich noch in Arbeit und soll die Befehlsauswahl auf Servern übersichtlicher machen.",
    skills: ["Java", "Minecraft", "Tab-Completer"],
    year: "2026",
    href: "https://github.com/DarkPlugins/RelevantCommandsOnly",
    download: "https://github.com/DarkPlugins/RelevantCommandsOnly/archive/refs/heads/main.zip",
    spigotHref: "https://www.spigotmc.org/resources/authors/nico336611.626286/"
  },
  {
    slug: "2fa",
    theme: "Minecraft Plugins",
    title: "2FA",
    status: "Finished",
    statusClass: "finished",
    description: "Ein Minecraft-Plugin, das Server mit einer Zwei-Faktor-Authentifizierung zusätzlich absichert.",
    details: "Der Fokus liegt auf einer zusätzlichen Sicherheitsschicht für Spieler und Serverzugänge.",
    skills: ["Java", "Minecraft", "Security"],
    year: "2026",
    href: "https://github.com/DarkPlugins/2FA",
    download: "https://github.com/DarkPlugins/2FA/archive/refs/heads/main.zip",
    spigotHref: "https://www.spigotmc.org/resources/simple-2fa.117855/"
  },
  {
    slug: "verifybot",
    theme: "Minecraft Plugins",
    title: "VerifyBot",
    status: "Active Development",
    statusClass: "active",
    statuses: [
      { label: "Not released yet", className: "not-released" },
      { label: "Active Development", className: "active" }
    ],
    description: "Ein Minecraft-Plugin, mit dem sich Spieler beispielsweise mit ihren Rängen auf einem Discord- und/oder TeamSpeak-Server verifizieren lassen.",
    details: "VerifyBot befindet sich aktuell in Entwicklung. Der Sourcecode ist nicht öffentlich verfügbar.",
    skills: ["Java", "Minecraft", "Discord", "TeamSpeak"],
    year: "2026",
    href: "https://www.spigotmc.org/resources/authors/nico336611.626286/",
    spigotHref: "https://www.spigotmc.org/resources/authors/nico336611.626286/",
    sourceAvailable: false
  },
  {
    slug: "ads",
    theme: "Minecraft Plugins",
    title: "Ads",
    status: "Finished",
    statusClass: "finished",
    description: "Ein Minecraft-Plugin, mit dem Spieler sich selbst oder ihren Plot auf einem CityBuild-Server bewerben können – inklusive direktem Teleport.",
    details: "Ads ist fertiggestellt. Die Werbung kann im Chat, in der Actionbar oder über weitere konfigurierbare Anzeigeformen erscheinen.",
    skills: ["Java", "Minecraft", "Spigot", "CityBuild"],
    year: "2025",
    href: "https://www.spigotmc.org/resources/ads-chat-advertising-with-teleport.114097/",
    spigotHref: "https://www.spigotmc.org/resources/ads-chat-advertising-with-teleport.114097/",
    sourceAvailable: false
  },
  {
    slug: "grs-v1",
    theme: "Prototypen & Hardware",
    title: "GamesRadioStation",
    status: "Prototype",
    statusClass: "prototype",
    description: "Ein Raspberry-Pi-Prototyp für eine spielbasierte Radio-Station mit Drehencoder, rundem LCD und Audioausgabe.",
    details: "Die Python-Anwendung verwaltet Spiele- und Songauswahl, speichert den Wiedergabestatus, steuert VLC und kann Audio über Bluetooth ausgeben. Das Projekt läuft unter Linux und integriert systemd für den Start beim Booten.",
    skills: ["Python", "Raspberry Pi", "Linux", "Bluetooth"],
    year: "2026",
    href: "https://github.com/DarkPlugins/GRS-v1",
    download: "https://github.com/DarkPlugins/GRS-v1/archive/refs/heads/main.zip"
  },
  {
    slug: "project-web-arcade",
    theme: "Prototypen & Hardware",
    title: "ProjectWebArcade",
    status: "Finished",
    statusClass: "finished",
    description: "Eine kompakte Arcade mit Browser-Spielen, echten Joysticks und Tastern.",
    details: "Der Launcher verbindet Snake, Pong und Quiz mit einem Node.js-Backend, das Hardware-Eingaben über WebSockets an die Weboberfläche weitergibt.",
    skills: ["HTML", "CSS", "JavaScript", "Node.js"],
    year: "2024",
    href: "https://github.com/DarkPlugins/ProjectWebArcade",
    download: "https://github.com/DarkPlugins/ProjectWebArcade/archive/refs/heads/main.zip"
  },
  {
    slug: "energy-analyzer-1-0",
    theme: "Tools & Analyse",
    title: "EnergyAnalyzer 1.0",
    status: "Finished",
    statusClass: "finished",
    sourcePrivate: true,
    sourceAvailable: false,
    description: "Eine Desktop-Anwendung zur Analyse erneuerbarer Energiedaten aus der SMARD-API.",
    details: "EnergyAnalyzer 1.0 unterstützt auswählbare Zeiträume, Tabellen- und Liniendiagramme sowie die lokale Speicherung von JSON-Daten. Es handelt sich um ein privates Projekt.",
    skills: ["C#", "SMARD API", "JSON", "Desktop"],
    year: "2026",
    href: null
  }
];
