globalThis.PROJECTS = [
  {
    slug: "ttvnotifyme",
    theme: "Web & Extensions",
    title: "TTVNotifyMe",
    image: "src/img/projects/ttvnotifyme/bel_01.webp",
    status: "finished",
    statusClass: "finished",
    description: "A browser extension that notifies you when a streamer goes live.",
    details: "TTVNotifyMe keeps an eye on streams without requiring the platform to stay open all the time.",
    skills: ["JavaScript", "Browser Extension", "Notifications"],
    year: "2026",
    href: "https://github.com/DarkPlugins/TTVNotifyMe",
    download: "https://github.com/DarkPlugins/TTVNotifyMe/archive/refs/heads/main.zip"
  },
  {
    slug: "media-downloader",
    theme: "Web & Extensions",
    title: "MediaDownloader",
    image: "src/img/projects/mediadownloader/bel_01.webp",
    status: "finished",
    statusClass: "finished",
    description: "A browser extension for downloading images and videos directly from the context menu.",
    details: "Media can be saved in its original format or in supported converted formats.",
    skills: ["JavaScript", "Browser Extension", "Media"],
    year: "2026",
    href: "https://github.com/DarkPlugins/MediaDownloader",
    download: "https://github.com/DarkPlugins/MediaDownloader/archive/refs/heads/main.zip"
  },
  {
    slug: "cr-toolkit",
    theme: "Web & Extensions",
    title: "CR-Toolkit",
    image: "src/img/projects/cr-toolkit/bel_01.webp",
    status: "active",
    statusClass: "active",
    description: "A Crunchyroll browser extension with additional controls for a more enjoyable anime experience.",
    details: "It includes an adjustable cinema mode, intro and outro skipping, and settings for the header and interface.",
    skills: ["JavaScript", "Browser Extension", "UI"],
    year: "2026",
    href: "https://github.com/DarkPlugins/CR-Toolkit",
    download: "https://github.com/DarkPlugins/CR-Toolkit/archive/refs/heads/main.zip"
  },
  {
    slug: "flipacoin",
    theme: "Web & Extensions",
    title: "FlipACoin",
    image: "src/img/projects/default.webp",
    status: "finished",
    statusClass: "finished",
    description: "A small website that simulates a coin flip quickly and simply.",
    details: "A deliberately compact web project that turns one idea into a clear interface.",
    skills: ["JavaScript", "HTML", "CSS"],
    year: "2026",
    href: "https://github.com/DarkPlugins/FlipACoin",
    download: "https://github.com/DarkPlugins/FlipACoin/archive/refs/heads/main.zip"
  },
  {
    slug: "web",
    theme: "Web & Extensions",
    title: "Web",
    image: "src/img/projects/default.webp",
    status: "finished",
    statusClass: "finished",
    description: "The personal website as a standalone web project.",
    details: "The repository contains the portfolio interface and its frontend implementation.",
    skills: ["HTML", "CSS", "JavaScript"],
    year: "2026",
    href: "https://github.com/DarkPlugins/Web",
    download: "https://github.com/DarkPlugins/Web/archive/refs/heads/main.zip"
  },
  {
    slug: "blacklist",
    theme: "Minecraft Plugins",
    title: "Blacklist",
    image: "src/img/projects/blacklist/pl_01.webp",
    status: "finished",
    statusClass: "finished",
    description: "A Minecraft plugin that blocks specific commands such as /plugins or /help for players.",
    details: "Blacklist is designed for German-speaking servers and focuses on one small, clearly defined protection feature.",
    skills: ["Java", "Minecraft", "Spigot"],
    year: "2024",
    href: "https://github.com/DarkPlugins/Blacklist",
    download: "https://github.com/DarkPlugins/Blacklist/archive/refs/heads/main.zip",
    spigotHref: "https://www.spigotmc.org/resources/blacklist-blocklist-de.114144/"
  },
  {
    slug: "relevant-commands-only",
    theme: "Minecraft Plugins",
    title: "RelevantCommandsOnly",
    image: "src/img/projects/default.webp",
    status: "notReleased",
    statusClass: "not-released",
    statuses: [
      { key: "notReleased", className: "not-released" },
      { key: "active", className: "active" }
    ],
    description: "A Minecraft plugin that shows only commands matching a player's preferences in tab completion.",
    details: "The project is still in development and aims to make command suggestions on servers more focused.",
    skills: ["Java", "Minecraft", "Tab Completer"],
    year: "≈ 2026–2027",
    href: "https://github.com/DarkPlugins/RelevantCommandsOnly",
    download: "https://github.com/DarkPlugins/RelevantCommandsOnly/archive/refs/heads/main.zip",
    spigotHref: "https://www.spigotmc.org/resources/authors/nico336611.626286/"
  },
  {
    slug: "2fa",
    theme: "Minecraft Plugins",
    title: "2FA",
    image: "src/img/projects/2fa/pl_01.webp",
    status: "finished",
    statusClass: "finished",
    description: "A Minecraft plugin that adds two-factor authentication to improve server security.",
    details: "The project adds an additional security layer for players and server access.",
    skills: ["Java", "Minecraft", "Security"],
    year: "2024",
    href: "https://github.com/DarkPlugins/2FA",
    download: "https://github.com/DarkPlugins/2FA/archive/refs/heads/main.zip",
    spigotHref: "https://www.spigotmc.org/resources/simple-2fa.117855/"
  },
  {
    slug: "verifybot",
    theme: "Minecraft Plugins",
    title: "VerifyBot",
    image: "src/img/projects/default.webp",
    status: "active",
    statusClass: "active",
    statuses: [
      { key: "notReleased", className: "not-released" },
      { key: "active", className: "active" }
    ],
    description: "A Minecraft plugin for verifying players, including their ranks, on a Discord and/or TeamSpeak server.",
    details: "VerifyBot is currently in development. The source code is not publicly available.",
    skills: ["Java", "Minecraft", "Discord", "TeamSpeak"],
    year: "2027",
    href: "https://www.spigotmc.org/resources/authors/nico336611.626286/",
    spigotHref: "https://www.spigotmc.org/resources/authors/nico336611.626286/",
    sourceAvailable: false
  },
  {
    slug: "ads",
    theme: "Minecraft Plugins",
    title: "Ads",
    image: "src/img/projects/ads/pl_01.webp",
    status: "finished",
    statusClass: "finished",
    description: "A Minecraft plugin for advertising yourself or your plot on a CityBuild server with direct teleportation.",
    details: "Ads is finished. Advertisements can appear in chat, the action bar, or other configurable display formats.",
    skills: ["Java", "Minecraft", "Spigot", "CityBuild"],
    year: "2023",
    href: "https://www.spigotmc.org/resources/ads-chat-advertising-with-teleport.114097/",
    spigotHref: "https://www.spigotmc.org/resources/ads-chat-advertising-with-teleport.114097/",
    sourceAvailable: false
  },
  {
    slug: "grs-v1",
    theme: "Prototypes & Hardware",
    title: "GamesRadioStation",
    image: "src/img/projects/grs/pt_01.webp",
    status: "prototype",
    statusClass: "prototype",
    description: "A Raspberry Pi prototype for a game-based radio station with a rotary encoder, round LCD, and audio output.",
    details: "The Python application manages game and song selection, saves playback state, controls VLC, and can output audio over Bluetooth. It runs on Linux and integrates systemd for boot startup.",
    skills: ["Python", "Raspberry Pi", "Linux", "Bluetooth"],
    year: "2025",
    href: "https://github.com/DarkPlugins/GRS-v1",
    download: "https://github.com/DarkPlugins/GRS-v1/archive/refs/heads/main.zip"
  },
  {
    slug: "arcade",
    theme: "Prototypes & Hardware",
    title: "Arcade",
    image: "src/img/projects/arcade/pt_01.webp",
    status: "finished",
    statusClass: "finished",
    sourcePrivate: true,
    sourceAvailable: false,
    description: "A small arcade machine built as a project with a friend using Node.js, HTML, CSS, JavaScript, and joystick integration.",
    details: "The source code is not public. There is no download or GitHub repository to take a look at.",
    skills: ["Node.js", "HTML", "CSS", "JavaScript", "Joystick Integration"],
    year: "2024",
    href: null
  },
  {
    slug: "energy-analyzer-1-0",
    theme: "Tools & Analysis",
    title: "EnergyAnalyzer 1.0",
    image: "src/img/projects/default.webp",
    status: "finished",
    statusClass: "finished",
    sourcePrivate: true,
    sourceAvailable: false,
    description: "A desktop application for analyzing renewable energy data from the SMARD API.",
    details: "EnergyAnalyzer 1.0 supports selectable time ranges, table and line chart visualization, and local JSON storage. It is a private project.",
    skills: ["C#", "SMARD API", "JSON", "Desktop"],
    year: "2026",
    href: null
  }
];
