globalThis.PROJECTS = [
  {
    slug: "ttvnotifyme",
    theme: "Web & Extensions",
    title: "TTVNotifyMe",
    image: "src/img/projects/ttvnotifyme/bel_01.webp",
    status: "finished",
    statusClass: "finished",
    description: "A browser extension that notifies you when a streamer goes live.",
    details: "TTVNotifyMe keeps an eye on streams without requiring the platform to stay open all the time.",
    descriptionDe: "Eine Browser-Erweiterung, die benachrichtigt, sobald ein Streamer live geht.",
    detailsDe: "TTVNotifyMe behält Streams im Blick, ohne dass die Plattform dauerhaft geöffnet bleiben muss.",
    skills: ["JavaScript", "Browser Extension", "Notifications"],
    skillsDe: ["JavaScript", "Browser-Erweiterung", "Benachrichtigungen"],
    year: "2026",
    href: "https://github.com/DarkPlugins/TTVNotifyMe",
    download: "https://github.com/DarkPlugins/TTVNotifyMe/archive/refs/heads/main.zip"
  },
  {
    slug: "media-downloader",
    theme: "Web & Extensions",
    title: "MediaDownloader",
    image: "src/img/projects/mediadownloader/bel_01.webp",
    status: "finished",
    statusClass: "finished",
    description: "A browser extension for downloading images and videos directly from the context menu.",
    details: "Media can be saved in its original format or in supported converted formats.",
    descriptionDe: "Eine Browser-Erweiterung zum Herunterladen von Bildern und Videos direkt aus dem Kontextmenü.",
    detailsDe: "Medien können im Originalformat oder in unterstützten konvertierten Formaten gespeichert werden.",
    skills: ["JavaScript", "Browser Extension", "Media"],
    skillsDe: ["JavaScript", "Browser-Erweiterung", "Medien"],
    year: "2026",
    href: "https://github.com/DarkPlugins/MediaDownloader",
    download: "https://github.com/DarkPlugins/MediaDownloader/archive/refs/heads/main.zip"
  },
  {
    slug: "cr-toolkit",
    theme: "Web & Extensions",
    title: "CR-Toolkit",
    image: "src/img/projects/cr-toolkit/bel_01.webp",
    status: "active",
    statusClass: "active",
    description: "A Crunchyroll browser extension with additional controls for a more enjoyable anime experience.",
    details: "It includes an adjustable cinema mode, intro and outro skipping, and settings for the header and interface.",
    descriptionDe: "Eine Crunchyroll-Browser-Erweiterung mit zusätzlichen Steuerelementen für ein angenehmeres Anime-Erlebnis.",
    detailsDe: "Enthalten sind ein anpassbarer Cinema-Modus, das Überspringen von Intros und Outros sowie Einstellungen für Kopfzeile und Oberfläche.",
    skills: ["JavaScript", "Browser Extension", "UI"],
    skillsDe: ["JavaScript", "Browser-Erweiterung", "Oberfläche"],
    year: "2026",
    href: "https://github.com/DarkPlugins/CR-Toolkit",
    download: "https://github.com/DarkPlugins/CR-Toolkit/archive/refs/heads/main.zip"
  },
  {
    slug: "flipacoin",
    theme: "Web & Extensions",
    title: "FlipACoin",
    image: "src/img/projects/default.webp",
    status: "finished",
    statusClass: "finished",
    description: "A small website that simulates a coin flip quickly and simply.",
    descriptionDe: "Eine kleine Website, die einen Münzwurf schnell und unkompliziert simuliert.",
    skills: ["JavaScript", "HTML", "CSS"],
    skillsDe: ["JavaScript", "HTML", "CSS"],
    year: "2026",
    href: "https://github.com/DarkPlugins/FlipACoin",
    download: "https://github.com/DarkPlugins/FlipACoin/archive/refs/heads/main.zip"
  },
  {
    slug: "web",
    theme: "Web & Extensions",
    title: "Web",
    image: "src/img/projects/default.webp",
    status: "finished",
    statusClass: "finished",
    description: "Well, it's just this website.",
    descriptionDe: "Das ist einfach diese Website.",
    skills: ["HTML", "CSS", "JavaScript"],
    skillsDe: ["HTML", "CSS", "JavaScript"],
    year: "2026",
    href: "https://github.com/DarkPlugins/Web",
    download: "https://github.com/DarkPlugins/Web/archive/refs/heads/main.zip"
  },
  {
    slug: "blacklist",
    theme: "Minecraft Plugins",
    title: "Blacklist",
    image: "src/img/projects/blacklist/pl_01.webp",
    status: "finished",
    statusClass: "finished",
    description: "A Minecraft plugin that blocks specific commands such as /plugins or /help for players.",
    details: "Blacklist is designed for German-speaking servers and focuses on one small, clearly defined protection feature.",
    descriptionDe: "Ein Minecraft-Plugin, das bestimmte Befehle wie /plugins oder /help für Spieler blockiert.",
    detailsDe: "Blacklist ist für deutschsprachige Server gedacht und konzentriert sich auf eine kleine, klar definierte Schutzfunktion.",
    skills: ["Java", "Minecraft", "Spigot"],
    skillsDe: ["Java", "Minecraft", "Spigot"],
    year: "2024",
    href: "https://github.com/DarkPlugins/Blacklist",
    download: "https://github.com/DarkPlugins/Blacklist/archive/refs/heads/main.zip",
    spigotHref: "https://www.spigotmc.org/resources/blacklist-blocklist-de.114144/"
  },
  {
    slug: "relevant-commands-only",
    theme: "Minecraft Plugins",
    title: "RelevantCommandsOnly",
    image: "src/img/projects/default.webp",
    status: "notReleased",
    statusClass: "not-released",
    statuses: [
      { key: "notReleased", className: "not-released" },
      { key: "active", className: "active" }
    ],
    description: "A Minecraft plugin that shows only commands matching a player's preferences in tab completion.",
    details: "The project is still in development and aims to make command suggestions on servers more focused.",
    descriptionDe: "Ein Minecraft-Plugin, das im Tab-Completer nur Befehle aus den persönlichen Präferenzen anzeigt.",
    detailsDe: "Das Projekt befindet sich noch in Entwicklung und soll die Befehlsauswahl auf Servern übersichtlicher machen.",
    skills: ["Java", "Minecraft", "Tab Completer"],
    skillsDe: ["Java", "Minecraft", "Tab-Vervollständigung"],
    year: "≈ 2026–2027",
    href: "https://github.com/DarkPlugins/RelevantCommandsOnly",
    download: "https://github.com/DarkPlugins/RelevantCommandsOnly/archive/refs/heads/main.zip",
    spigotHref: "https://www.spigotmc.org/resources/authors/nico336611.626286/"
  },
  {
    slug: "2fa",
    theme: "Minecraft Plugins",
    title: "2FA",
    image: "src/img/projects/2fa/pl_01.webp",
    status: "finished",
    statusClass: "finished",
    description: "A Minecraft plugin that adds two-factor authentication to improve server security.",
    details: "The project adds an additional security layer for players and server access.",
    descriptionDe: "Ein Minecraft-Plugin, das Server mit einer Zwei-Faktor-Authentifizierung zusätzlich absichert.",
    detailsDe: "Der Fokus liegt auf einer zusätzlichen Sicherheitsschicht für Spieler und Serverzugänge.",
    skills: ["Java", "Minecraft", "Security"],
    skillsDe: ["Java", "Minecraft", "Sicherheit"],
    year: "2024",
    href: "https://github.com/DarkPlugins/2FA",
    download: "https://github.com/DarkPlugins/2FA/archive/refs/heads/main.zip",
    spigotHref: "https://www.spigotmc.org/resources/simple-2fa.117855/"
  },
  {
    slug: "verifybot",
    theme: "Minecraft Plugins",
    title: "VerifyBot",
    image: "src/img/projects/default.webp",
    status: "active",
    statusClass: "active",
    statuses: [
      { key: "notReleased", className: "not-released" },
      { key: "active", className: "active" }
    ],
    description: "A Minecraft plugin for verifying players, including their ranks, on a Discord and/or TeamSpeak server.",
    details: "VerifyBot is currently in development. The source code is not publicly available.",
    descriptionDe: "Ein Minecraft-Plugin, mit dem sich Spieler beispielsweise mit ihren Rängen auf einem Discord- und/oder TeamSpeak-Server verifizieren lassen.",
    detailsDe: "VerifyBot befindet sich aktuell in Entwicklung. Der Quellcode ist nicht öffentlich verfügbar.",
    skills: ["Java", "Minecraft", "Discord", "TeamSpeak"],
    skillsDe: ["Java", "Minecraft", "Discord", "TeamSpeak"],
    year: "2027",
    href: "https://www.spigotmc.org/resources/authors/nico336611.626286/",
    spigotHref: "https://www.spigotmc.org/resources/authors/nico336611.626286/",
    sourceAvailable: false
  },
  {
    slug: "ads",
    theme: "Minecraft Plugins",
    title: "Ads",
    image: "src/img/projects/ads/pl_01.webp",
    status: "finished",
    statusClass: "finished",
    description: "A Minecraft plugin for advertising yourself or your plot on a CityBuild server with direct teleportation.",
    details: "Ads is finished. Advertisements can appear in chat, the action bar, or other configurable display formats.",
    descriptionDe: "Ein Minecraft-Plugin, mit dem Spieler sich selbst oder ihren Plot auf einem CityBuild-Server bewerben können – inklusive direktem Teleport.",
    detailsDe: "Ads ist fertiggestellt. Die Werbung kann im Chat, in der Actionbar oder über weitere konfigurierbare Anzeigeformen erscheinen.",
    skills: ["Java", "Minecraft", "Spigot", "CityBuild"],
    skillsDe: ["Java", "Minecraft", "Spigot", "CityBuild"],
    year: "2023",
    href: "https://www.spigotmc.org/resources/ads-chat-advertising-with-teleport.114097/",
    spigotHref: "https://www.spigotmc.org/resources/ads-chat-advertising-with-teleport.114097/",
    sourceAvailable: false
  },
  {
    slug: "grs-v1",
    theme: "Prototypes & Hardware",
    title: "GamesRadioStation",
    image: "src/img/projects/grs/pt_01.webp",
    status: "prototype",
    statusClass: "prototype",
    description: "A Raspberry Pi prototype for a game-based radio station with a rotary encoder, round LCD, and audio output.",
    details: "The Python application manages game and song selection, saves playback state, controls VLC, and can output audio over Bluetooth. It runs on Linux and integrates systemd for boot startup.",
    descriptionDe: "Ein Raspberry-Pi-Prototyp für eine spielbasierte Radio-Station mit Drehencoder, rundem LCD und Audioausgabe.",
    detailsDe: "Die Python-Anwendung verwaltet Spiele- und Songauswahl, speichert den Wiedergabestatus, steuert VLC und kann Audio über Bluetooth ausgeben. Das Projekt läuft unter Linux und integriert systemd für den Start beim Booten.",
    skills: ["Python", "Raspberry Pi", "Linux", "Bluetooth"],
    skillsDe: ["Python", "Raspberry Pi", "Linux", "Bluetooth"],
    year: "2025",
    href: "https://github.com/DarkPlugins/GRS-v1",
    download: "https://github.com/DarkPlugins/GRS-v1/archive/refs/heads/main.zip"
  },
  {
    slug: "arcade",
    theme: "Prototypes & Hardware",
    title: "Arcade",
    image: "src/img/projects/arcade/pt_01.webp",
    status: "finished",
    statusClass: "finished",
    sourcePrivate: false,
    sourceAvailable: true,
    description: "A small arcade machine built as a project with a friend using Node.js, HTML, CSS, JavaScript, and joystick integration.",
    details: "The source code is public. However, the background videos are not included because they are too large for GitHub.",
    descriptionDe: "Als Projektarbeit mit einem Freund entstand eine kleine Arcademaschine mit Node.js, HTML, CSS, JavaScript und Joystick-Integration.",
    detailsDe: "Der Quellcode ist öffentlich, allerdings sind die Hintergrundvideos nicht vorhanden, da diese zu groß für Github sind.",
    skills: ["Node.js", "HTML", "CSS", "JavaScript", "Joystick Integration"],
    skillsDe: ["Node.js", "HTML", "CSS", "JavaScript", "Joystick-Integration"],
    year: "2024",
    href: "https://github.com/DarkPlugins/Arcade",
    download: "https://github.com/DarkPlugins/Arcade/archive/refs/heads/main.zip"
  },
  {
    slug: "energy-analyzer-1-0",
    theme: "Tools & Analysis",
    title: "EnergyAnalyzer 1.0",
    image: "src/img/projects/default.webp",
    status: "finished",
    statusClass: "finished",
    sourcePrivate: true,
    sourceAvailable: false,
    description: "A desktop application for analyzing renewable energy data from the SMARD API.",
    details: "EnergyAnalyzer 1.0 supports selectable time ranges, table and line chart visualization, and local JSON storage. It is a private project.",
    descriptionDe: "Eine Desktop-Anwendung zur Analyse erneuerbarer Energiedaten aus der SMARD API.",
    detailsDe: "EnergyAnalyzer 1.0 unterstützt auswählbare Zeiträume, Tabellen- und Liniendiagramme sowie die lokale Speicherung von JSON-Daten. Es handelt sich um ein privates Projekt.",
    skills: ["C#", "SMARD API", "JSON", "Desktop"],
    skillsDe: ["C#", "SMARD API", "JSON", "Desktop"],
    year: "2026",
    href: null
  }
];
